apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-b
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/degwinthegreat/k8s_learning
    targetRevision: HEAD
    path: manifests/app-b
  destination:
    server: https://kubernetes.default.svc
    namespace: app-b
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # クラスター再作成時、Gateway APIのCRD導入完了までHTTPRouteの同期に失敗するためリトライする
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m