apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    # Roadie ArgoCDプラグインが同期状態を表示するためのApplication名
    argocd/app-name: ${{ values.name }}
    backstage.io/source-location: url:https://github.com/degwinthegreat/k8s_learning/tree/main/manifests/${{ values.name }}/
spec:
  type: service
  lifecycle: experimental
  owner: guests
